# Version: 0.0.1
FROM ubuntu:17.04
MAINTAINER zhuanxu "893051481@qq.com"

WORKDIR /opt
VOLUME ["/opt"]
RUN apt-get update
RUN apt-get install -y cmake
RUN apt-get install -y build-essential
RUN apt-get install -y man
